### ISSUE TITLE
Couldn't build robot shop from source

### ISSUE THREAD

**Issue by AntoniusFirst** [instana/robot-shop#5] opened 2018-05-11 13:09 UTC
Hi, guys

Please check attached output from building docker image. There is a problem with command docker-compose build and asking for files from link https://oss.risingstack.com/repo/v1/@risingstack/profiler/dist/v5.7.11

So we can't make build.

[robot-shop-output-install.txt](https://github.com/instana/robot-shop/files/1995361/robot-shop-output-install.txt)

**Comment by AntoniusFirst** [comment] 2018-05-11 13:45
> @risingstack/v8-profiler@5.7.11 install /opt/server/node_modules/@risingstack/v8-profiler
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://oss.risingstack.com/repo/v1/@risingstack/profiler/dist/v5.7.11/node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for @risingstack/v8-profiler@5.7.11 and node@8.11.1 (node-v57 ABI) (falling back to source compile with node-gyp)
make: Entering directory '/opt/server/node_modules/@risingstack/v8-profiler/build'
  CXX(target) Release/obj.target/profiler/src/profiler.o
  CXX(target) Release/obj.target/profiler/src/cpu_profiler.o
  CXX(target) Release/obj.target/profiler/src/cpu_profile.o
  CXX(target) Release/obj.target/profiler/src/cpu_profile_node.o
  CXX(target) Release/obj.target/profiler/src/heap_profiler.o
../src/heap_profiler.cc: In member function 'virtual v8::ActivityControl::ControlOption nodex::ActivityControlAdapter::ReportProgressValue(int, int)':
../src/heap_profiler.cc:35:18: warning: 'v8::TryCatch::TryCatch()' is deprecated (declared at /root/.node-gyp/8.11.1/include/node/v8.h:8313): Use isolate version [-Wdeprecated-declarations]
         TryCatch try_catch;
                  ^
../src/heap_profiler.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE nodex::HeapProfiler::TakeSnapshot(Nan::NAN_METHOD_ARGS_TYPE)':
../src/heap_profiler.cc:70:29: warning: unused variable 'control' [-Wunused-variable]
     ActivityControlAdapter* control = new ActivityControlAdapter(info[1]);
                             ^
  CXX(target) Release/obj.target/profiler/src/heap_snapshot.o
  CXX(target) Release/obj.target/profiler/src/heap_output_stream.o
../src/heap_output_stream.cc: In member function 'virtual void nodex::OutputStreamAdapter::EndOfStream()':
../src/heap_output_stream.cc:17:14: warning: 'v8::TryCatch::TryCatch()' is deprecated (declared at /root/.node-gyp/8.11.1/include/node/v8.h:8313): Use isolate version [-Wdeprecated-declarations]
     TryCatch try_catch;
              ^
../src/heap_output_stream.cc: In member function 'virtual v8::OutputStream::WriteResult nodex::OutputStreamAdapter::WriteAsciiChunk(char*, int)':
../src/heap_output_stream.cc:37:14: warning: 'v8::TryCatch::TryCatch()' is deprecated (declared at /root/.node-gyp/8.11.1/include/node/v8.h:8313): Use isolate version [-Wdeprecated-declarations]
     TryCatch try_catch;
              ^
../src/heap_output_stream.cc: In member function 'virtual v8::OutputStream::WriteResult nodex::OutputStreamAdapter::WriteHeapStatsChunk(v8::HeapStatsUpdate*, int)':
../src/heap_output_stream.cc:61:14: warning: 'v8::TryCatch::TryCatch()' is deprecated (declared at /root/.node-gyp/8.11.1/include/node/v8.h:8313): Use isolate version [-Wdeprecated-declarations]
     TryCatch try_catch;
              ^
  CXX(target) Release/obj.target/profiler/src/heap_graph_node.o
../src/heap_graph_node.cc: In static member function 'static v8::Local<v8::Value> nodex::GraphNode::New(const v8::HeapGraphNode*)':
../src/heap_graph_node.cc:69:24: warning: 'bool v8::Object::Has(uint32_t)' is deprecated (declared at /root/.node-gyp/8.11.1/include/node/v8.h:3171): Use maybe version [-Wdeprecated-declarations]
     if (_cache->Has(_id)) {
                        ^
  CXX(target) Release/obj.target/profiler/src/heap_graph_edge.o
  SOLINK_MODULE(target) Release/obj.target/profiler.node
  COPY Release/profiler.node
  COPY /opt/server/node_modules/@risingstack/v8-profiler/build/@risingstack/profiler/v5.7.11/node-v57-linux-x64/profiler.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/opt/server/node_modules/@risingstack/v8-profiler/build'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN catalogue@1.0.0 No repository field.

**Comment by steveww** [comment] 2018-05-11 14:04
Must be something unique to your environment. I just did a complete clean and build of the whole thing and it all worked just fine. May be you have some firewall/proxy settings that are messing you up. Can you get to that site from the command line e.g. via curl?

**Comment by steveww** [comment] 2018-05-11 14:10
If you read the message, it failed to download a pre-build binary, then went on to actually build the binary from source. No error, just a warning.

**Comment by AntoniusFirst** [comment] 2018-05-11 14:14
We've tried from curl

root@monitoringhost:~# curl https://oss.risingstack.com/repo/v1/@risingstack/profiler/dist/v5.7.11/node-v57-linux-x64.tar.gz
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>repo/v1/@risingstack/profiler/dist/v5.7.11/node-v57-linux-x64.tar.gz</Key><RequestId>B241D138FFB16583</RequestId><HostId>844j2QWufJ996fL0SITLshJC5mXyIo68wKSebznA1RVLM7KmyFGjVlb7SPWjc/r3O5URi9VNuPA=</HostId></Error>root@monitoringhost:~#

**Comment by AntoniusFirst** [comment] 2018-05-11 14:15
Guess, this is an error

node-pre-gyp ERR! Tried to download(404): https://oss.risingstack.com/repo/v1/@risingstack/profiler/dist/v5.7.11/node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for @risingstack/v8-profiler@5.7.11 and node@8.11.1 (node-v57 ABI) (falling back to source compile with node-gyp)

**Comment by kcrawley** [comment] 2018-05-11 15:02
The issue is actually further along in your build log. It has to do with the point in which the mysql build process is trying to launch mysqld in order to seed the database. I was not able to replicate the error either. Can you please provide the output of:

`docker info` and `docker-compose version`

**Comment by kcrawley** [comment] 2018-05-11 15:07
@steveww i think the issue may be around the `mysqladmin shutdown` in https://github.com/instana/robot-shop/blob/master/shipping/database/Dockerfile#L14

it may be prudent here to just return true if that command fails. it's entirely possible the user is hitting a race condition here and the daemon is already shut down.

**Comment by AntoniusFirst** [comment] 2018-05-11 15:08
root@monitoringhost:~# docker info
Containers: 124
 Running: 102
 Paused: 0
 Stopped: 22
Images: 54
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796GiB
Name: monitoringhost.ru
ID: ZWKZ:T5ZZ:QQCE:PISJ:NE7Y:4IR3:HE2R:FUVQ:TJ4F:VCR2:ASUU:TQL4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Comment by kcrawley** [comment] 2018-05-11 15:47
@AntoniusFirst I have a workaround for you while I wait to hear back from @steveww on a proper fix.

https://github.com/instana/robot-shop/blob/master/shipping/database/Dockerfile#L14

find this file locally and adjust the `do sleep 10` to `do sleep 30`, then issue a `docker-compose build mysql`, and let me know the results

---

@steveww I was able to reproduce the issue by reducing the sleep timeout to `1`

```
2018-05-11T15:37:56.604870Z 0 [Note] InnoDB: FTS optimize thread exiting.
2018-05-11T15:37:56.605068Z 0 [Note] InnoDB: Starting shutdown...
2018-05-11T15:37:56.705423Z 0 [Note] InnoDB: Dumping buffer pool(s) to /data/mysql/ib_buffer_pool
2018-05-11T15:37:56.706217Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 180511 15:37:56
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
ERROR: Service 'mysql' failed to build: The command '/bin/sh -c /entrypoint.sh mysqld & while [ ! -f /tmp/finished ]; do sleep 1; done && mysqladmin shutdown' returned a non-zero code: 1
```
the issue appears to be that once the `rs-shipping-db` image build process finishes seeding its database, the process ensures that mysqld can be booted up and then shutdown. the issue is wait time after the initial seed is not long enough on the machine the end user is building on because I suspect with its current workload there just isn't enough compute to get through that process fast enough.

my recommendation would be to wait for the `/tmp/finished` file to appear, then begin looking for the `mysqld` process to be running and then proceed to shutdown. as a preventative measure against hung builds, perhaps set a 5 minute timeout.

**Comment by steveww** [comment] 2018-05-11 16:32
OK, I can see what could be happening on a slow machine. I will have a look at it and give it a little tweak. I guess not everybody has a MacBook Pro with 16GB all to themselves ;-)

**Comment by AntoniusFirst** [comment] 2018-05-11 17:38
@steveww this is VM from public cloud with 4 cores and 8 Gb RAM. Hope, this is enough :) I can share with you access to this VM and you will see the issue from firsthand. This VM is just for demo and there is no any important data on it. If it will be suitable for you, I will be glad to receive message to my street-ag@yandex.ru with your contact info.

The main goal is to demonstrate Instana's features to our customer and as I know Instana's agent can't run on MAC OS.

**Comment by steveww** [comment] 2018-05-14 08:08
Could be done to IO latency then, it's importing a large database during the build. I will give it a try on a well know cloud provider. By the way all the Docker images are already built and available from Docker Hub. You can get started without building from source.

**Comment by steveww** [comment] 2018-05-14 10:15
Reproduced the problem on a well known cloud provider. Pushed a fix and rebuilt the images on Docker Hub.

**Closed by steveww** 2018-05-14 10:15 UTC
